# Cleaning fav-trees.csv

In [1]:
import pandas as pd
df = pd.read_csv("fav-trees.csv")

# drop first column
df = df.drop(columns= ["Unnamed: 0"])
df

,treeId,numberOfTimesFavorited,objectid,dbh,tpstructure,tpcondition,plantingspaceglobalid,geometry,globalid,genusspecies,...,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location.type,location.coordinates,riskrating,riskratingdate,planteddate,stumpdiameter
0,90423,1,90423,8.0,Retired,Dead,710AE376-7FD6-4146-B5A8-1174A4DBCADA,POINT(-73.99352652018682 40.72203588035812),3F232143-9B90-4E43-85F1-D2FB0589FDCB,Pyrus calleryana - Callery pear,...,57.0,4.0,32.0,2.0,Point,"[-73.99352652018682, 40.72203588035812]",7.0,2022-06-13 15:33:00.0000000,NaN,10.0
1,104829,1,104829,45.0,Retired,Fair,88C09F4C-305B-4E8F-BC03-31653501DFFB,POINT(-74.09148027469415 40.62210244322464),DD0D6B40-EEDA-4B3A-966D-7FFE204D9E0D,Platanus x acerifolia - London planetree,...,4.0,1.0,13.0,74.0,Point,"[-74.09148027469415, 40.62210244322464]",7.0,2023-02-20 18:01:24.0000000,NaN,NaN
2,108832,1,108832,36.0,Full,Fair,FB016AF0-5BF7-49B0-AA42-4273DFE53E53,POINT(-73.93789425172587 40.639669330061984),21941BE1-1A3F-4864-AB82-B7B6B79C06C2,Quercus velutina - black oak,...,61.0,2.0,26.0,40.0,Point,"[-73.93789425172587, 40.639669330061984]",7.0,2022-03-01 16:52:50.0000000,NaN,NaN
3,118055,1,118055,27.0,Full,Good,B43DA448-2ACD-4F5A-87D4-B974659A71B0,POINT(-73.92749692304744 40.761994762991634),250EA4AC-602D-4500-9C92-1001D846468D,Platanus x acerifolia - London planetree,...,39.0,3.0,4.0,72.0,Point,"[-73.92749692304744, 40.761994762991634]",7.0,2025-02-18 14:14:22.0000000,NaN,NaN
4,136058,1,136058,19.0,Full,Fair,79B126FA-B397-45B5-AEC1-DC584E21552C,POINT(-73.84730966248289 40.84143160163848),C227A560-218A-486B-852B-C6F814778541,Styphnolobium japonicum - Japanese pagoda tree,...,43.0,5.0,12.0,28.0,Point,"[-73.84730966248289, 40.84143160163848]",6.0,2025-02-27 15:35:25.0000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5097,5603877,1,5603877,12.0,Full,Good,949BC853-E713-4103-BA3E-CFF89440B6DD,POINT(-73.900295397453 40.69920174620001),75BB9305-DE9E-4FFA-B8DA-B125DD18689D,Tilia cordata - littleleaf linden,...,54.0,3.0,30.0,62.0,Point,"[-73.900295397453, 40.69920174620001]",NaN,NaN,NaN,NaN
5098,5603878,1,5603878,7.0,Full,Poor,D18F1B12-CE35-46F3-96CC-91D2544B186A,POINT(-73.89989094760251 40.69960643829981),1CB23CAE-479F-45C8-AF48-DA3FBE959B58,Tilia cordata - littleleaf linden,...,54.0,3.0,30.0,62.0,Point,"[-73.89989094760251, 40.69960643829981]",7.0,2025-09-17 18:00:13.0000000,NaN,NaN
5099,5603879,1,5603879,15.0,Full,Good,AA572909-F4BA-4DFB-B4CA-DBC1DFC34ACA,POINT(-73.89981726414555 40.69968261813123),F104B9EC-F36A-4F20-BEC6-DC1AAEFE2C97,Tilia cordata - littleleaf linden,...,54.0,3.0,30.0,62.0,Point,"[-73.89981726414555, 40.69968261813123]",NaN,NaN,NaN,NaN
5100,5603880,1,5603880,4.0,Full,Good,E62F5FB9-BB24-4FAC-96F4-E24BDB8C1612,POINT(-73.89913900988743 40.699381578851245),EF430F30-1917-4C6F-BD99-183596C63842,Tilia cordata - littleleaf linden,...,54.0,3.0,30.0,62.0,Point,"[-73.89913900988743, 40.699381578851245]",NaN,NaN,NaN,NaN
5101,5603881,1,5603881,2.0,Full,Good,9D918D5D-0826-43D4-A8FA-063B4FE13E12,POINT(-73.89931811899537 40.69919851551673),4FAD38A6-8993-4FF6-93DA-4F125E84D07B,Cladrastis kentukea - Kentucky yellowwood,...,54.0,3.0,30.0,62.0,Point,"[-73.89931811899537, 40.69919851551673]",NaN,NaN,2016-11-24 05:00:00.0000000,NaN

In [2]:
df.columns

Index(['treeId', 'numberOfTimesFavorited', 'objectid', 'dbh', 'tpstructure',
       'tpcondition', 'plantingspaceglobalid', 'geometry', 'globalid',
       'genusspecies', 'createddate', 'updateddate',
       ':@computed_region_efsh_h5xi', ':@computed_region_f5dn_yrer',
       ':@computed_region_yeji_bk3q', ':@computed_region_92fq_4b7q',
       ':@computed_region_sbqj_enih', 'location.type', 'location.coordinates',
       'riskrating', 'riskratingdate', 'planteddate', 'stumpdiameter'],
      dtype='str')

In [3]:
# split genusspecies column into two columns - latin name & common name

df[['latin_name', 'common_name']] = df['genusspecies'].str.split('-', n=1, expand=True)

In [4]:
# check work
df[['genusspecies','latin_name', "common_name"]]

,genusspecies,latin_name,common_name
0,Pyrus calleryana - Callery pear,Pyrus calleryana,Callery pear
1,Platanus x acerifolia - London planetree,Platanus x acerifolia,London planetree
2,Quercus velutina - black oak,Quercus velutina,black oak
3,Platanus x acerifolia - London planetree,Platanus x acerifolia,London planetree
4,Styphnolobium japonicum - Japanese pagoda tree,Styphnolobium japonicum,Japanese pagoda tree
...,...,...,...
5097,Tilia cordata - littleleaf linden,Tilia cordata,littleleaf linden
5098,Tilia cordata - littleleaf linden,Tilia cordata,littleleaf linden
5099,Tilia cordata - littleleaf linden,Tilia cordata,littleleaf linden
5100,Tilia cordata - littleleaf linden,Tilia cordata,littleleaf linden
5101,Cladrastis kentukea - Kentucky yellowwood,Cladrastis kentukea,Kentucky yellowwood

In [5]:
# get rid of any trailing spaces

df['common_name'] = df['common_name'].str.strip()

In [6]:
df_checkwork = df[['genusspecies','common_name']]
df_checkwork.head()

                                     genusspecies           common_name
0                 Pyrus calleryana - Callery pear          Callery pear
1        Platanus x acerifolia - London planetree      London planetree
2                    Quercus velutina - black oak             black oak
3        Platanus x acerifolia - London planetree      London planetree
4  Styphnolobium japonicum - Japanese pagoda tree  Japanese pagoda tree

In [7]:
df['common_name'] = df['common_name'].str.strip("'")
df['common_name'] = df['common_name'].str.capitalize()
df['common_name'] = df['common_name'].str.strip("'")
df['common_name'] = (df['common_name'].str.replace("'", ""))
df['common_name']

0               Callery pear
1           London planetree
2                  Black oak
3           London planetree
4       Japanese pagoda tree
                ...
5097       Littleleaf linden
5098       Littleleaf linden
5099       Littleleaf linden
5100       Littleleaf linden
5101     Kentucky yellowwood
Name: common_name, Length: 5102, dtype: str

In [8]:
## create 2 new columns for location coordinates

# split into two columns based on delimiter ","
df[['long', 'lat']] = df['location.coordinates'].str.split(',', n=1, expand=True)

# then get rid of brackets
df['long'] = df['long'].str.strip("[")
df['lat'] = df['lat'].str.strip("]")

In [ ]:
# check work
df[['lat', 'long']]

#### Save cleaned version to new .csv file

In [10]:
df.to_csv('fav-trees-clean.csv', index=False)

In [11]:
df.value_counts("common_name").head(10)

common_name
Thornless honeylocust                   660
London planetree                        404
Callery pear                            385
Pin oak                                 385
Maidenhair tree                         352
Japanese pagoda tree                    340
Japanese zelkova                        237
Littleleaf linden                       236
Green leaf japanese flowering cherry    123
American elm                            110
Name: count, dtype: int64

#### Create another .csv with data for only the top 5 favorite types of trees

In [44]:
top5_favs = (df.query('common_name == "Callery pear" or common_name == "London planetree" or common_name == "Thornless honeylocust" or common_name == "Pin oak" or common_name == "Maidenhair tree"'))
top5_favs.to_csv('top5_favs.csv', index=False)