# Get Data on Favorite Trees

link to data: https://data.cityofnewyork.us/Environment/NYC-Street-Tree-Map-Favorite-Trees/pbi9-jd5i/about_data

In [1]:
import pandas as pd
import json
with open('favorite-trees.json') as file:    
    data = json.load(file)

In [ ]:
# drop the metadata at the top of the .json so that I convert this into a pandas dataframe
df_fav = pd.json_normalize(data['data'])

In [3]:
df_fav.dtypes

treeId                    int64
numberOfTimesFavorited    int64
dtype: object

In [4]:
df_fav.shape

(5171, 2)

# Get Forestry Tree Points Data

link to data: https://data.cityofnewyork.us/Environment/Forestry-Tree-Points/hn5i-inap/about_data

Note: this dataset has >1.1 million rows. I requested it 99,999 rows at a time, merging each set of 99,999 rows with the favorite tree data using an inner join.

#### get first 99,999 rows

In [5]:
import requests
url = 'https://data.cityofnewyork.us/resource/hn5i-inap.json?$limit=99999'
response = requests.get(url)

data = response.json()

In [6]:
df = pd.json_normalize(data)
df.head()

,objectid,dbh,tpstructure,tpcondition,plantingspaceglobalid,geometry,globalid,genusspecies,createddate,updateddate,...,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location.type,location.coordinates,riskrating,riskratingdate,planteddate,stumpdiameter
0,86823,22,Retired,Excellent,E814CD37-9F53-4D79-AF86-3B454F9D29B9,POINT(-73.81656874596392 40.716290654685075),2B457A4C-E0E4-4E17-81C4-A5449F51C804,Acer nigrum - black maple,2015-02-28 05:00:00.0000000,2026-01-03 13:52:00.0000000,...,25,3,24,65,Point,"[-73.81656874596392, 40.716290654685075]",NaN,NaN,NaN,NaN
1,87623,10,Retired,Good,A644AB79-A3CB-4F7F-923B-F308E615CCD4,POINT(-73.93848036135195 40.81299277914583),37195E1A-A7EE-4AA4-8389-19A0ED5C46F7,Fraxinus pennsylvanica - Green ash,2015-03-03 05:00:00.0000000,2019-09-18 13:12:55.0000000,...,18,4,36,20,Point,"[-73.93848036135195, 40.81299277914583]",NaN,NaN,NaN,NaN
2,88023,24,Retired,Poor,21431016-EDB8-4A0B-B122-673125800C87,POINT(-73.8324418090213 40.88762504315543),6BA8E72B-1901-4EF3-ABFF-D11680AB4A9B,Acer platanoides - Norway maple,2015-03-03 05:00:00.0000000,2018-03-27 14:00:42.0000000,...,29,5,2,30,Point,"[-73.8324418090213, 40.88762504315543]",NaN,NaN,NaN,NaN
3,88823,10,Full,Fair,96FB6C55-612F-466D-9449-85A3CD2178E1,POINT(-74.20903635163978 40.519577813518666),79A5DBAF-F305-4DA1-A4B1-7A8C8D085435,Pyrus calleryana - Callery pear,2015-03-04 05:00:00.0000000,2024-06-28 12:41:55.0000000,...,15,1,9,77,Point,"[-74.20903635163978, 40.519577813518666]",6,2024-06-28 12:41:55.0000000,NaN,NaN
4,88824,10,Retired,Dead,4796B64F-906C-4345-A4E9-5CD6133642F8,POINT(-73.98032166282525 40.7429106380851),182F6647-D9C1-4A45-ADA0-9ADEFD1ECC60,Gleditsia triacanthos var. inermis - Thornless...,2015-03-04 05:00:00.0000000,2016-10-24 02:50:43.0000000,...,71,4,50,7,Point,"[-73.98032166282525, 40.7429106380851]",NaN,NaN,NaN,NaN

In [7]:
df.dtypes

objectid                          str
dbh                               str
tpstructure                       str
tpcondition                       str
plantingspaceglobalid             str
geometry                          str
globalid                          str
genusspecies                      str
createddate                       str
updateddate                       str
:@computed_region_efsh_h5xi       str
:@computed_region_f5dn_yrer       str
:@computed_region_yeji_bk3q       str
:@computed_region_92fq_4b7q       str
:@computed_region_sbqj_enih       str
location.type                     str
location.coordinates           object
riskrating                        str
riskratingdate                    str
planteddate                       str
stumpdiameter                     str
dtype: object

In [8]:
# convert objectid field from string to integer to prepare for merging data

df['objectid'] = pd.to_numeric(df['objectid'])

# perform inner join using ID fields - treeID and objectID
df_0 = df_fav.merge(df, how='inner', left_on='treeId', right_on='objectid')
df_0

,treeId,numberOfTimesFavorited,objectid,dbh,tpstructure,tpcondition,plantingspaceglobalid,geometry,globalid,genusspecies,...,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location.type,location.coordinates,riskrating,riskratingdate,planteddate,stumpdiameter
0,90423,1,90423,8,Retired,Dead,710AE376-7FD6-4146-B5A8-1174A4DBCADA,POINT(-73.99352652018682 40.72203588035812),3F232143-9B90-4E43-85F1-D2FB0589FDCB,Pyrus calleryana - Callery pear,...,57,4,32,2,Point,"[-73.99352652018682, 40.72203588035812]",7,2022-06-13 15:33:00.0000000,NaN,10
1,104829,1,104829,45,Retired,Fair,88C09F4C-305B-4E8F-BC03-31653501DFFB,POINT(-74.09148027469415 40.62210244322464),DD0D6B40-EEDA-4B3A-966D-7FFE204D9E0D,Platanus x acerifolia - London planetree,...,4,1,13,74,Point,"[-74.09148027469415, 40.62210244322464]",7,2023-02-20 18:01:24.0000000,NaN,NaN
2,108832,1,108832,36,Full,Fair,FB016AF0-5BF7-49B0-AA42-4273DFE53E53,POINT(-73.93789425172587 40.639669330061984),21941BE1-1A3F-4864-AB82-B7B6B79C06C2,Quercus velutina - black oak,...,61,2,26,40,Point,"[-73.93789425172587, 40.639669330061984]",7,2022-03-01 16:52:50.0000000,NaN,NaN
3,118055,1,118055,27,Full,Good,B43DA448-2ACD-4F5A-87D4-B974659A71B0,POINT(-73.92749692304744 40.761994762991634),250EA4AC-602D-4500-9C92-1001D846468D,Platanus x acerifolia - London planetree,...,39,3,4,72,Point,"[-73.92749692304744, 40.761994762991634]",7,2025-02-18 14:14:22.0000000,NaN,NaN
4,136058,1,136058,19,Full,Fair,79B126FA-B397-45B5-AEC1-DC584E21552C,POINT(-73.84730966248289 40.84143160163848),C227A560-218A-486B-852B-C6F814778541,Styphnolobium japonicum - Japanese pagoda tree,...,43,5,12,28,Point,"[-73.84730966248289, 40.84143160163848]",6,2025-02-27 15:35:25.0000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,1402836,1,1402836,6,Full,Good,3476A2F9-CF19-40F5-AECF-049030D40D81,POINT(-73.92849916919721 40.85357953043017),C42A6226-3DCD-4E87-A024-BE6D5A3177D3,Koelreuteria paniculata - goldenrain tree,...,47,4,39,22,Point,"[-73.92849916919721, 40.85357953043017]",3,2021-11-24 17:01:22.0000000,NaN,NaN
782,1402837,1,1402837,7,Full,Good,4904F6B3-EDF1-4B05-B223-F1C808657E48,POINT(-73.92856365255972 40.853606693192425),759AF59E-1265-4671-8A95-5815A68D0A31,Koelreuteria paniculata - goldenrain tree,...,47,4,39,22,Point,"[-73.92856365255972, 40.853606693192425]",3,2021-11-24 17:02:52.0000000,NaN,NaN
783,1403871,1,1403871,13,Retired,Unknown,A3D79C70-F7F2-44B2-9000-B3646D090121,POINT(-73.78788337741908 40.73922776072113),A801291C-F514-416B-B2CB-75031A234F1F,Fraxinus pennsylvanica - Green ash,...,25,3,16,65,Point,"[-73.78788337741908, 40.73922776072113]",3,2018-07-05 10:59:58.0000000,NaN,0
784,1403872,1,1403872,23,Retired,Unknown,457E35E0-8643-4203-AC4A-89B6462CAA31,POINT(-73.78793472015043 40.73933709957778),57D940D3-CE96-4B30-8346-80C363ABA59B,Platanus x acerifolia - London planetree,...,25,3,16,65,Point,"[-73.78793472015043, 40.73933709957778]",3,2018-07-05 11:02:05.0000000,NaN,0
785,1403873,1,1403873,23,Retired,Unknown,8DA6A85B-6C1F-4531-9065-0E20B0506FE6,POINT(-73.78798254221054 40.73943894159301),AF06399E-BA64-4033-AABA-AB5F8684A339,Platanus x acerifolia - London planetree,...,25,3,16,65,Point,"[-73.78798254221054, 40.73943894159301]",3,2018-07-05 11:03:02.0000000,NaN,0

#### get rows 100,000-199,999

In [9]:
import requests
url = 'https://data.cityofnewyork.us/resource/hn5i-inap.json?$limit=99999&$offset=99999'
response = requests.get(url)

data = response.json()

In [10]:
df = pd.json_normalize(data)
df.head()

,objectid,dbh,tpstructure,tpcondition,plantingspaceglobalid,geometry,globalid,genusspecies,createddate,updateddate,...,riskratingdate,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location.type,location.coordinates,stumpdiameter,planteddate
0,1404139,7,Full,Fair,626AFD60-61ED-49E9-80D5-F8CE16F2DCEF,POINT(-73.93101446212427 40.85392960492108),67A5DDE6-0904-4630-B25F-06E1553F8D81,Ulmus parvifolia - Chinese elm,2015-10-29 13:11:34.0000000,2021-11-23 18:13:40.0000000,...,2021-11-23 18:13:40.0000000,13098,47,4,39,22,Point,"[-73.93101446212427, 40.85392960492108]",NaN,NaN
1,1404140,6,Full,Good,C864C84C-E6FD-4F11-938E-65049DB124B4,POINT(-73.93089420325484 40.85387863928989),831E80AD-AF33-4E9E-AE73-AAFAA9C2481E,Ulmus parvifolia - Chinese elm,2015-10-29 13:11:34.0000000,2021-11-23 18:12:31.0000000,...,2021-11-23 18:12:31.0000000,13098,47,4,39,22,Point,"[-73.93089420325484, 40.85387863928989]",NaN,NaN
2,1404141,8,Full,Good,6E6D1160-9C21-4B08-A7FD-5A0DC382CC0A,POINT(-73.9307954069831 40.85383676794611),BB3D2C7A-7C0E-4F3D-A98F-DAD8A3E3400C,Ulmus parvifolia - Chinese elm,2015-10-29 13:11:35.0000000,2021-11-23 18:11:12.0000000,...,2021-11-23 18:11:12.0000000,13098,47,4,39,22,Point,"[-73.9307954069831, 40.85383676794611]",NaN,NaN
3,1404142,2,Full,Good,6708CCE7-D4D9-43DA-82D9-7B01EA1CFB86,POINT(-73.9309722836584 40.85326688481507),45289CB7-2A63-4E4B-AED6-83D91EAAC98A,Eucommia ulmoides - Hardy Rubber Tree,2015-10-29 13:11:35.0000000,2017-10-24 08:01:16.0000000,...,NaN,13098,47,4,39,22,Point,"[-73.9309722836584, 40.85326688481507]",0,NaN
4,1404143,2,Full,Good,41704860-7FBC-4D65-BE3B-1099B7D4A7E4,POINT(-73.93089465446302 40.85337260434166),E3D063ED-1EA0-4217-AAF3-54CD116257E7,Eucommia ulmoides - Hardy Rubber Tree,2015-10-29 13:11:35.0000000,2017-10-24 08:02:45.0000000,...,NaN,13098,47,4,39,22,Point,"[-73.93089465446302, 40.85337260434166]",0,NaN

In [11]:
# convert objectid field from string to integer to prepare for merging data

df['objectid'] = pd.to_numeric(df['objectid'])

# perform inner join using ID fields - treeID and objectID
df_1 = df_fav.merge(df, how='inner', left_on='treeId', right_on='objectid')
df_1

,treeId,numberOfTimesFavorited,objectid,dbh,tpstructure,tpcondition,plantingspaceglobalid,geometry,globalid,genusspecies,...,riskratingdate,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location.type,location.coordinates,stumpdiameter,planteddate
0,1404456,1,1404456,26,Full,Fair,960E20C1-71D9-4E52-948C-5D403D643070,POINT(-73.79486636441031 40.77306966631531),0B00EA07-D36A-4913-A125-DCA4D96E8BF0,Morus - mulberry,...,NaN,14193,22,3,20,67,Point,"[-73.79486636441031, 40.77306966631531]",0,NaN
1,1404499,1,1404499,3,Full,Fair,AC3856AC-3AE2-478D-BF8D-EE8A64DEA9BE,POINT(-73.7932584782461 40.77654531065604),A8B21D27-8702-45CC-9EFC-E77934F788B7,Malus - apple,...,NaN,14192,22,3,20,67,Point,"[-73.7932584782461, 40.77654531065604]",0,NaN
2,1404575,1,1404575,25,Full,Good,FCDDCB66-85B2-48B2-8DD9-6094EB95ACC6,POINT(-73.77949452860183 40.78481188201859),08AF0696-D450-4A98-BD59-D7824B8FAD01,Morus - mulberry,...,2025-08-14 14:46:32.0000000,14195,22,3,20,67,Point,"[-73.77949452860183, 40.78481188201859]",0,NaN
3,1404763,1,1404763,27,Full,Fair,528CDF89-476D-4767-A002-9BDAC024BFD1,POINT(-74.00230970054896 40.64600504797424),4F573358-820D-4471-9481-0428D67D632A,Platanus x acerifolia - London planetree,...,2022-08-12 13:29:07.0000000,18180,9,2,7,45,Point,"[-74.00230970054896, 40.64600504797424]",NaN,NaN
4,1405005,1,1405005,24,Full,Fair,B8EDBDEF-D858-418E-AD66-6CF888CD6698,POINT(-73.89872637391946 40.75552777887057),E1BDC180-7D7E-462A-9FC4-568C91EFDE5F,Quercus palustris - pin oak,...,2025-10-30 14:27:08.0000000,14787,65,3,5,73,Point,"[-73.89872637391946, 40.75552777887057]",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1684,2151501,1,2151501,13,Full,Fair,3009120A-F625-4701-AFE9-348D42EC911E,POINT(-73.98470107596539 40.73621435119117),39A9ED19-BCD4-47C5-AFAD-051428A62F1F,Platanus x acerifolia - London planetree,...,2024-01-12 15:02:37.0000000,11724,71,4,50,7,Point,"[-73.98470107596539, 40.73621435119117]",NaN,NaN
1685,2151502,1,2151502,11,Full,Good,ED89B663-5B2E-4C35-9B44-2FC61C4F286D,POINT(-73.9846073032014 40.73617488572906),A50CC91A-A64A-4F3E-AC52-A7E47B474A5B,Gleditsia triacanthos var. inermis - Thornless...,...,2024-01-12 14:59:58.0000000,11724,71,4,50,7,Point,"[-73.9846073032014, 40.73617488572906]",NaN,NaN
1686,2151503,1,2151503,9,Full,Good,3D26054B-87A9-4BEF-926F-98CBB2243D71,POINT(-73.98451384550208 40.736135551180276),58DC7172-471B-45E7-A062-870175EF63B4,Gleditsia triacanthos var. inermis - Thornless...,...,2024-01-12 14:58:32.0000000,11724,71,4,50,7,Point,"[-73.98451384550208, 40.736135551180276]",NaN,NaN
1687,2173517,2,2173517,8,Retired,Unknown,6559933B-AA2F-406F-A68C-CE09B2D4526C,POINT(-73.99204302945382 40.69172696059057),870DD864-7AE8-47FB-AAE5-E18F4A7117D9,Pyrus calleryana - Callery pear,...,NaN,16865,68,2,38,54,Point,"[-73.99204302945382, 40.69172696059057]",0,NaN
1688,2190717,1,2190717,50,Full,Poor,9BD03CF4-98F8-4004-A012-48C3893576D1,POINT(-73.77263827895632 40.757839577610206),D8C54219-2C73-454B-8FF5-B0253335A56D,Fraxinus - Ash,...,2025-11-21 18:54:14.0000000,14196,26,3,20,69,Point,"[-73.77263827895632, 40.757839577610206]",NaN,NaN

#### get rows 200,000-299,999

In [12]:
import requests
url = 'https://data.cityofnewyork.us/resource/hn5i-inap.json?$limit=99999&$offset=199999'
response = requests.get(url)

data = response.json()

In [13]:
df = pd.json_normalize(data)
df.head()

,objectid,dbh,tpstructure,tpcondition,plantingspaceglobalid,geometry,globalid,genusspecies,createddate,updateddate,...,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location.type,location.coordinates,riskrating,riskratingdate,stumpdiameter,planteddate
0,2199160,16,Retired,Dead,DC760110-1A17-4A06-AE03-5F9CE0F7D837,POINT(-73.91512638146904 40.663825605940524),52914D3F-7676-49BB-B78D-829049500989,Zelkova serrata - Japanese zelkova,2016-01-16 12:08:00.0000000,2019-03-13 18:11:25.0000000,...,55,2,17,46,Point,"[-73.91512638146904, 40.663825605940524]",NaN,NaN,NaN,NaN
1,2199161,26,Full,Fair,0F4EC4F0-F608-4468-8004-AD740663B8C7,POINT(-73.91512954903668 40.664323645128164),89910E58-78CD-447F-A837-4880801333C8,Quercus palustris - pin oak,2016-01-16 12:01:03.0000000,2021-01-29 14:52:20.0000000,...,55,2,17,46,Point,"[-73.91512954903668, 40.664323645128164]",NaN,NaN,NaN,NaN
2,2199162,11,Full,Fair,ACD43ECC-22B5-4116-B571-DC1309C8CCC8,POINT(-73.91717712924323 40.667850283558536),627ACD1F-A4D5-4D03-B86B-6833322463A0,Malus - apple,2016-01-16 11:31:20.0000000,2021-01-28 19:22:27.0000000,...,55,2,17,46,Point,"[-73.91717712924323, 40.667850283558536]",NaN,NaN,NaN,NaN
3,2199163,5,Full,Good,F1310457-D0C4-4D45-B34B-85FBF30BF104,POINT(-73.91666685666524 40.67526077645632),1B9C590B-97AC-4846-9C8A-4861F8A22614,Gleditsia triacanthos var. inermis - Thornless...,2016-01-16 11:21:00.0000000,2019-05-10 17:53:25.0000000,...,55,2,17,46,Point,"[-73.91666685666524, 40.67526077645632]",3,2019-05-10 13:53:24.0000000,NaN,NaN
4,2199164,21,Full,Fair,D5CF2AA1-B6D2-4F51-A599-165CE2E5B063,POINT(-73.90526721861659 40.67648722038339),3111F931-DD48-4EEA-8FB3-96E1F4FA787F,Gleditsia triacanthos var. inermis - Thornless...,2016-01-16 11:11:00.0000000,2025-12-02 17:25:53.0000000,...,55,2,37,46,Point,"[-73.90526721861659, 40.67648722038339]",7,2025-12-02 17:25:53.0000000,NaN,NaN

In [14]:
# convert objectid field from string to integer to prepare for merging data

df['objectid'] = pd.to_numeric(df['objectid'])

# perform inner join using ID fields - treeID and objectID
df_2 = df_fav.merge(df, how='inner', left_on='treeId', right_on='objectid')
df_2

,treeId,numberOfTimesFavorited,objectid,dbh,tpstructure,tpcondition,plantingspaceglobalid,geometry,globalid,genusspecies,...,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location.type,location.coordinates,riskrating,riskratingdate,stumpdiameter,planteddate
0,2229553,1,2229553,17,Full,Poor,3D27D114-76DB-41EA-B785-F0880B8DA40E,POINT(-73.99412601750163 40.72450883245147),36000349-F332-424B-B216-BD9F9B5189CF,Pyrus calleryana - Callery pear,...,57,4,32,2,Point,"[-73.99412601750163, 40.72450883245147]",8,2025-07-15 18:56:35.0000000,NaN,NaN
1,2230752,1,2230752,33,Full,Fair,F841B6DA-69FD-4662-9E73-29EFED62EF31,POINT(-73.95726963542874 40.63558599350365),B0387342-A260-430C-A994-66966C584723,Ulmus pumila - Siberian elm,...,60,2,26,43,Point,"[-73.95726963542874, 40.63558599350365]",7,2021-10-21 15:46:45.0000000,NaN,NaN
2,2231953,1,2231953,40,Full,Critical,3BC4E679-31C3-4BFC-9D20-08981A8E5EF8,POINT(-73.96043063083945 40.63473676034232),7A96DBC0-3D6C-4F5C-BB37-98910CA20E02,Ulmus americana - American elm,...,60,2,26,43,Point,"[-73.96043063083945, 40.63473676034232]",11,2017-05-24 14:00:41.0000000,NaN,NaN
3,2240257,1,2240257,11,Full,Fair,1534976C-FDBC-4366-B260-1D4540C31DE4,POINT(-73.91092765708639 40.88688811154051),3EB4CC6E-7BD8-4E95-80F4-F6327BD7C4AF,Ginkgo biloba - maidenhair tree,...,48,5,40,33,Point,"[-73.91092765708639, 40.88688811154051]",6,2022-05-04 18:16:33.0000000,NaN,NaN
4,2240316,1,2240316,14,Full,Fair,B8D84B3D-BD23-486B-9F84-200048E3558A,POINT(-73.89725335105209 40.86126812158545),D8D7FAA7-2A03-49AF-975F-4A8C40418C19,Ginkgo biloba - maidenhair tree,...,6,5,22,29,Point,"[-73.89725335105209, 40.86126812158545]",NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,2537284,1,2537284,20,Retired,Unknown,C1DA7B40-A576-4A37-8667-0E64674C3D00,POINT(-73.95268757836534 40.720032618079905),6F99C5F5-5122-46D3-9AC7-2C16688576CD,Platanus x acerifolia - London planetree,...,36,2,38,57,Point,"[-73.95268757836534, 40.720032618079905]",9,2020-03-31 13:38:00.0000000,34,NaN
671,2537285,1,2537285,24,Retired,Unknown,BAB1488C-2B6D-46CB-B237-633BBC980055,POINT(-73.95270369270436 40.72013121874889),A4DD9329-5161-43AE-B2EA-B2D9FE6863CD,Platanus x acerifolia - London planetree,...,36,2,38,57,Point,"[-73.95270369270436, 40.72013121874889]",8,2020-03-10 15:16:00.0000000,48,NaN
672,2537400,2,2537400,22,Full,Fair,AB37D487-4A03-49C1-AA3F-F1DD4DE55352,POINT(-73.94720083751488 40.73007370089157),32F873FC-3E51-4083-8FFA-078333CB17A6,Populus deltoides - eastern cottonwood,...,36,2,38,57,Point,"[-73.94720083751488, 40.73007370089157]",7,2024-05-22 16:58:48.0000000,NaN,NaN
673,2537578,1,2537578,4,Full,Good,44B36674-4DDB-4C6D-B951-648801B72107,POINT(-73.89613958484554 40.85986807482699),7788E1AD-34AD-4487-BFC5-D4760A704B75,Acer rubrum - red maple,...,6,5,22,29,Point,"[-73.89613958484554, 40.85986807482699]",NaN,NaN,0,NaN
674,2537590,1,2537590,2,Retired,Good,EE3D64BC-F64B-454B-A0B3-7DA7E67EB632,POINT(-73.8960819766473 40.859200301130876),E09C0A80-6D10-49A4-849C-85E9792FBBC9,Quercus acutissima - sawtooth oak,...,6,5,22,29,Point,"[-73.8960819766473, 40.859200301130876]",NaN,NaN,0,NaN

#### get rows 300,000-399,999

In [15]:
import requests
url = 'https://data.cityofnewyork.us/resource/hn5i-inap.json?$limit=99999&$offset=299999'
response = requests.get(url)

data = response.json()

In [16]:
df = pd.json_normalize(data)
df.head()

,objectid,dbh,tpstructure,tpcondition,stumpdiameter,plantingspaceglobalid,geometry,globalid,genusspecies,createddate,...,riskrating,riskratingdate,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location.type,location.coordinates,planteddate
0,2537785,7,Retired,Dead,8,C5AA9485-2F98-4795-91B7-DE0430B36809,POINT(-73.99968944477406 40.68707195892095),2F055CD3-FBA6-495E-9451-C918C3755592,Acer platanoides - Norway maple,2016-02-12 14:31:00.0000000,...,7,2018-08-22 10:32:00.0000000,13514,14,2,27,48,Point,"[-73.99968944477406, 40.68707195892095]",NaN
1,2537786,22,Full,Fair,NaN,B13A0011-5CC6-4B4C-8D24-398DEF245D8D,POINT(-73.90644229088468 40.818027419401105),91E3EC32-868A-408C-9E18-6B1D12FA6015,Platanus x acerifolia - London planetree,2016-02-12 14:31:52.0000000,...,6,2023-06-20 12:09:04.0000000,10933,49,5,43,23,Point,"[-73.90644229088468, 40.818027419401105]",NaN
2,2537787,23,Full,Fair,NaN,161358F9-8875-4FC9-B321-F618B0DED495,POINT(-73.90647838060418 40.8179387930617),095FBE68-14F2-4005-B0DC-EA63BD542023,Platanus x acerifolia - London planetree,2016-02-12 14:31:52.0000000,...,5,2023-06-20 12:11:31.0000000,10933,49,5,43,23,Point,"[-73.90647838060418, 40.8179387930617]",NaN
3,2537788,7,Retired,Unknown,7,A8B5385C-FAE2-4FDF-A343-1B82EAE593F1,POINT(-73.90651853060724 40.81784020151958),BF510537-1F7F-4BE7-BBE3-BA01DD9010B9,Unknown - Unknown,2016-02-12 14:31:00.0000000,...,NaN,NaN,10933,49,5,43,23,Point,"[-73.90651853060724, 40.81784020151958]",NaN
4,2537789,27,Full,Fair,NaN,183B7654-1E79-4F7C-9247-5F48C7F838EF,POINT(-73.90655622206906 40.81774764120867),E87652F8-78F6-475A-9872-C35358E85966,Platanus x acerifolia - London planetree,2016-02-12 14:31:52.0000000,...,5,2023-06-20 12:14:30.0000000,10933,49,5,43,23,Point,"[-73.90655622206906, 40.81774764120867]",NaN

In [17]:
# convert objectid field from string to integer to prepare for merging data

df['objectid'] = pd.to_numeric(df['objectid'])

# perform inner join using ID fields - treeID and objectID
df_3 = df_fav.merge(df, how='inner', left_on='treeId', right_on='objectid')
df_3

,treeId,numberOfTimesFavorited,objectid,dbh,tpstructure,tpcondition,stumpdiameter,plantingspaceglobalid,geometry,globalid,...,riskrating,riskratingdate,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location.type,location.coordinates,planteddate
0,2537898,1,2537898,7,Full,Good,0,2A61B6CD-DBC8-4E55-8568-E65185364067,POINT(-73.89514441001731 40.86075551894122),4A952EDA-6014-448F-9A77-B8285561D1BB,...,NaN,NaN,10936,6,5,22,29,Point,"[-73.89514441001731, 40.86075551894122]",NaN
1,2538423,1,2538423,5,Full,Good,0,92A8468A-4D98-4339-84AB-2A3D8109B94A,POINT(-73.93393235718543 40.58445964661802),6190EFC2-6ABA-467E-82C9-AFC2CD7E6A76,...,NaN,NaN,13826,32,2,15,36,Point,"[-73.93393235718543, 40.58445964661802]",NaN
2,2539106,1,2539106,8,Full,Good,NaN,2F8C2C6B-F355-4D7F-8703-A81FBB77F0CA,POINT(-73.9897893014513 40.6783684429324),AF607190-81C2-4175-8FE0-3097D9C2C27A,...,6,2026-03-20 14:53:24.0000000,13514,14,2,27,48,Point,"[-73.9897893014513, 40.6783684429324]",NaN
3,2539107,1,2539107,10,Full,Good,NaN,F5B8345F-D48B-4A38-AC0B-E12D82FD1CD1,POINT(-73.98985511799329 40.67839404148235),075F6329-E690-4C43-9A38-312002499AE2,...,6,2026-03-20 14:51:32.0000000,13514,14,2,27,48,Point,"[-73.98985511799329, 40.67839404148235]",NaN
4,2539108,1,2539108,7,Full,Fair,NaN,6FC88507-386A-4BC8-B820-AEAAF3967CA2,POINT(-73.99011742180916 40.67849606296218),73675DB1-2F81-424E-9E6B-406809A161F6,...,6,2026-03-20 14:09:19.0000000,13514,14,2,27,48,Point,"[-73.99011742180916, 40.67849606296218]",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,2918460,1,2918460,8,Full,Fair,0,5CF53878-3CE4-4771-A2F1-1160797C519C,POINT(-74.15378842560392 40.54897425012881),F3F84959-9EC6-4DC0-9724-533FCE7EABD0,...,NaN,NaN,10695,15,1,9,76,Point,"[-74.15378842560392, 40.54897425012881]",NaN
227,2919645,1,2919645,17,Full,Fair,NaN,D88F1C0F-6485-4E4B-95CF-2A1AFEE5D2FF,POINT(-74.21817293406322 40.54309486886018),6D0AB7C4-FD2B-4A70-B137-101EF93D25AF,...,8,2024-12-11 19:52:38.0000000,10696,15,1,9,77,Point,"[-74.21817293406322, 40.54309486886018]",NaN
228,2919646,1,2919646,11,Full,Fair,0,5657BAC2-F3B7-4785-8FB1-9047504C0641,POINT(-74.21826499597448 40.54307205885869),CE1492EA-52C8-407B-A4FB-F5CAEFC64BAB,...,NaN,NaN,10696,15,1,9,77,Point,"[-74.21826499597448, 40.54307205885869]",NaN
229,2920378,1,2920378,21,Full,Good,NaN,6E778414-9794-4672-9E70-A7F9A0A5F445,POINT(-74.12264408836913 40.62126283570712),4D2B195B-EC47-4BB0-B51B-F70A16C06F9E,...,6,2025-11-24 17:48:56.0000000,10700,4,1,14,74,Point,"[-74.12264408836913, 40.62126283570712]",NaN
230,2922008,1,2922008,49,Full,Unknown,NaN,98D92016-06C2-4429-9D22-C699C92496CB,POINT(-74.10260812635313 40.612679065792676),98563761-55EE-44D4-AFDA-D95F30D15E5D,...,3,2025-12-26 16:54:00.0000000,10369,4,1,13,74,Point,"[-74.10260812635313, 40.612679065792676]",NaN

#### get rows 400,000-499,999

In [18]:
# get next set of data
import requests
url = 'https://data.cityofnewyork.us/resource/hn5i-inap.json?$limit=99999&$offset=399999'
response = requests.get(url)

data = response.json()


# convert from json to pandas dataframe
df = pd.json_normalize(data)


# convert objectid field from string to integer to prepare for merging data
df['objectid'] = pd.to_numeric(df['objectid'])


# perform inner join using ID fields - treeID and objectID
df_4 = df_fav.merge(df, how='inner', left_on='treeId', right_on='objectid')
df_4

,treeId,numberOfTimesFavorited,objectid,dbh,tpstructure,tpcondition,plantingspaceglobalid,geometry,globalid,genusspecies,...,riskratingdate,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location.type,location.coordinates,stumpdiameter,planteddate
0,2927994,1,2927994,5,Full,Excellent,BDA159C9-DDAA-4E15-ACE5-58354AFFB192,POINT(-74.1120838246234 40.56796983951264),D325E4B8-3DD2-41DC-96EA-0F5632281EE7,Cornus mas - Cornelian cherry,...,2025-06-05 12:40:10.0000000,10693,30,1,14,76,Point,"[-74.1120838246234, 40.56796983951264]",NaN,NaN
1,2928416,1,2928416,4,Full,Poor,8F147C6C-4395-48D0-AB58-C5323EA86EF7,POINT(-74.15356211107094 40.62845379062575),02913226-15A7-466B-A550-269CAAC85E14,Prunus serrulata 'Green leaf' - 'Green leaf' J...,...,NaN,10371,4,1,13,75,Point,"[-74.15356211107094, 40.62845379062575]",0,NaN
2,2928579,1,2928579,8,Full,Good,C4DD645F-5EB2-47E8-AE7C-FCAFFB9439A3,POINT(-74.14353884755347 40.627430035626126),B52CEEDA-622A-400E-B299-FA671131942B,Pyrus calleryana - Callery pear,...,2022-03-25 14:35:37.0000000,10370,4,1,13,75,Point,"[-74.14353884755347, 40.627430035626126]",NaN,NaN
3,2929860,1,2929860,2,Retired,Fair,9B121D9A-C33A-4017-A4C2-61D9CDA8EAC9,POINT(-74.1365008157192 40.55114836000465),69E0893C-EAE0-4A2E-AAAB-2933F41BD229,Zelkova serrata - Japanese zelkova,...,NaN,10695,15,1,9,76,Point,"[-74.1365008157192, 40.55114836000465]",0,NaN
4,2929867,1,2929867,27,Full,Fair,ACC05145-C764-4E52-83E9-9A458D1D3EA0,POINT(-74.13428388812889 40.560547217108834),738BA510-3512-40A9-8A53-A6D25C5F20B2,Quercus palustris - pin oak,...,2022-02-18 17:37:55.0000000,10693,15,1,9,76,Point,"[-74.13428388812889, 40.560547217108834]",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,3744435,1,3744435,15,Full,Fair,AE81567C-3273-48E4-AE7F-83683195E438,POINT(-73.97877867864484 40.65798837000681),CEE586D4-F639-4682-AD32-7C7ECF06C5C3,Pyrus calleryana - Callery pear,...,2025-02-18 18:55:09.0000000,17617,9,2,27,45,Point,"[-73.97877867864484, 40.65798837000681]",NaN,NaN
708,3744459,1,3744459,14,Full,Good,9D4AB10D-DF21-4353-8DC1-F646CBA16AF6,POINT(-73.95682648342665 40.68650681943527),667A0A27-67E2-4CE1-9391-5ABB7C940838,Gleditsia triacanthos var. inermis - Thornless...,...,NaN,13829,69,2,48,51,Point,"[-73.95682648342665, 40.68650681943527]",0,NaN
709,3744478,1,3744478,10,Full,Fair,36322D46-DDE0-4535-B256-03CA12C0CFB4,POINT(-73.92872520137976 40.68167877568902),755E4991-46BA-4AD5-92EB-FCACB9A8CAB5,Pyrus calleryana - Callery pear,...,2024-02-14 15:56:16.0000000,13516,69,2,49,52,Point,"[-73.92872520137976, 40.68167877568902]",NaN,NaN
710,3744872,1,3744872,12,Full,Good,0003D2EE-909F-4B58-949D-4113132117A9,POINT(-73.98475470139029 40.6460405554446),3CACB6E2-08EA-4133-B343-C438AC12F8EE,Liquidambar styraciflua - sweetgum,...,NaN,17617,9,2,7,45,Point,"[-73.98475470139029, 40.6460405554446]",0,NaN
711,3744880,1,3744880,6,Full,Good,6BD26033-9F7C-45DE-90FA-AB996D6C8898,POINT(-73.89937819234936 40.749491758949),E2E07B3F-62CD-4A90-8A33-6383A1AB4A3B,Quercus robur - English oak,...,2022-03-10 14:18:22.0000000,14787,53,3,33,66,Point,"[-73.89937819234936, 40.749491758949]",NaN,NaN

#### get rows 500,000-599,999

In [19]:
# get next set of data
import requests
url = 'https://data.cityofnewyork.us/resource/hn5i-inap.json?$limit=99999&$offset=499999'
response = requests.get(url)

data = response.json()


# convert from json to pandas dataframe
df = pd.json_normalize(data)


# convert objectid field from string to integer to prepare for merging data
df['objectid'] = pd.to_numeric(df['objectid'])


# perform inner join using ID fields - treeID and objectID
df_5 = df_fav.merge(df, how='inner', left_on='treeId', right_on='objectid')
df_5

,treeId,numberOfTimesFavorited,objectid,dbh,tpstructure,tpcondition,stumpdiameter,plantingspaceglobalid,geometry,globalid,...,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location.type,location.coordinates,riskrating,riskratingdate,planteddate
0,3745080,1,3745080,16,Full,Good,NaN,5F43D442-474C-4F2C-98FC-C3B44DCC0F4B,POINT(-73.97755512023987 40.657396395091226),A7950A72-247A-4137-8103-974445B7D182,...,17617,9,2,27,45,Point,"[-73.97755512023987, 40.657396395091226]",7,2024-07-22 17:06:29.0000000,NaN
1,3745174,1,3745174,17,Full,Fair,NaN,B9D11065-F185-42B3-96C3-6735D6E1558C,POINT(-73.94195466407565 40.69852312534389),2DD3D56F-9CF6-492B-A863-9C74B19E65D7,...,17213,69,2,49,51,Point,"[-73.94195466407565, 40.69852312534389]",6,2025-06-03 13:22:51.0000000,NaN
2,3745527,1,3745527,12,Full,Fair,NaN,ADBE3E3C-AF93-492E-9895-7CA88361CB57,POINT(-73.96602834953299 40.68823841650832),CCE972C0-6908-4146-B502-3AF61B2D0B36,...,17212,68,2,48,55,Point,"[-73.96602834953299, 40.68823841650832]",5,2026-02-05 16:11:17.0000000,NaN
3,3745624,1,3745624,21,Full,Good,0,6075A3C0-2EF4-4258-9720-2B879EB863FE,POINT(-74.00712705020266 40.64688073777772),81257A74-3E57-4BE5-A95C-A2A8474D60FA,...,18180,9,2,7,45,Point,"[-74.00712705020266, 40.64688073777772]",6,2020-10-09 18:23:03.0000000,NaN
4,3745705,1,3745705,12,Full,Fair,NaN,7054DD85-BCDB-4F04-AEFA-7BE12A52480A,POINT(-73.95550697518877 40.69188483515383),61AFB219-01F8-4B10-8EBE-68C44BE2B57A,...,17212,69,2,38,51,Point,"[-73.95550697518877, 40.69188483515383]",7,2025-07-07 14:36:54.0000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,4139877,1,4139877,32,Retired,Dead,0,8D922224-5992-4B1F-A869-091CECD21AF4,POINT(-73.79782643181298 40.72184717320434),1D3545FB-4A5F-4256-A33E-CD58A9046A7E,...,24340,25,3,24,65,Point,"[-73.79782643181298, 40.72184717320434]",7,2018-03-28 12:11:05.0000000,NaN
365,4140663,1,4140663,2,Retired,Good,0,7B312B86-3A7E-4B3D-8F59-0192FF7FDFAD,POINT(-73.92636114407304 40.75404410066701),3CC7ADB5-4712-4DC3-98B1-C7FE6381846F,...,16863,39,3,33,72,Point,"[-73.92636114407304, 40.75404410066701]",NaN,NaN,NaN
366,4141054,1,4141054,42,Retired,Dead,42,B71E9537-0008-489C-A1DD-A51CAF3EA1E3,POINT(-74.03464776913516 40.61147176693373),7C96EE1A-CA51-48EA-8D1A-D8ABFD1467DB,...,17216,10,2,44,41,Point,"[-74.03464776913516, 40.61147176693373]",10,2021-06-09 15:20:00.0000000,NaN
367,4141624,1,4141624,15,Full,Fair,NaN,4BFF4EEF-E16A-4310-A3E9-82BFCD8B63F6,POINT(-73.95686075469617 40.613138442841915),9E8D7BEE-204E-4AC2-96D9-C07627F68EBA,...,13513,60,2,15,43,Point,"[-73.95686075469617, 40.613138442841915]",6,2025-10-15 17:47:00.0000000,NaN
368,4141725,1,4141725,30,Full,Fair,NaN,2E2859DD-7D22-41B8-88E6-8CBE4AC08FB2,POINT(-73.82777463968225 40.76418272220952),85B40A63-1D23-484D-9CD5-7ED8F599B570,...,13832,22,3,3,67,Point,"[-73.82777463968225, 40.76418272220952]",7,2025-10-15 13:56:45.0000000,NaN

#### get rows 600,000-699,999

In [20]:
# get next set of data
import requests
url = 'https://data.cityofnewyork.us/resource/hn5i-inap.json?$limit=99999&$offset=599999'
response = requests.get(url)

data = response.json()


# convert from json to pandas dataframe
df = pd.json_normalize(data)


# convert objectid field from string to integer to prepare for merging data
df['objectid'] = pd.to_numeric(df['objectid'])


# perform inner join using ID fields - treeID and objectID
df_6 = df_fav.merge(df, how='inner', left_on='treeId', right_on='objectid')
df_6

,treeId,numberOfTimesFavorited,objectid,dbh,tpstructure,tpcondition,plantingspaceglobalid,geometry,globalid,genusspecies,...,riskratingdate,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location.type,location.coordinates,stumpdiameter,planteddate
0,4142561,1,4142561,11,Full,Good,85B014C0-817E-4DF0-9FBF-A5D803D64BEC,POINT(-74.1840865295985 40.521287246665004),4C74455F-84E0-4978-91DF-41D986A19659,Pyrus calleryana - Callery pear,...,NaN,10699,15,1,9,77,Point,"[-74.1840865295985, 40.521287246665004]",0,NaN
1,4142702,1,4142702,6,Retired,Fair,B0EEC249-2826-4410-8F2A-2BD072313876,POINT(-74.03091484276037 40.61772952263563),006EBEC3-0396-44F0-AE51-0C4E982173F6,Pyrus calleryana - Callery pear,...,2019-10-31 15:28:45.0000000,17216,10,2,44,41,Point,"[-74.03091484276037, 40.61772952263563]",0,NaN
2,4142941,1,4142941,18,Full,Good,C1721137-27CF-4444-8194-8EB776FF5DB4,POINT(-74.01951875871936 40.633225783435826),5EBD5FAB-216E-4D7E-B187-FF215E1E108A,Platanus x acerifolia - London planetree,...,2021-08-12 18:26:49.0000000,18180,10,2,44,41,Point,"[-74.01951875871936, 40.633225783435826]",NaN,NaN
3,4143548,1,4143548,7,Full,Fair,465078E1-BB98-4E80-8D19-E455E8CFE8CD,POINT(-73.82423479593596 40.671074043425186),8C500752-CDBD-448E-9B9A-D9C8B931ACB9,Pyrus calleryana - Callery pear,...,2025-12-22 14:09:27.0000000,24016,62,3,41,64,Point,"[-73.82423479593596, 40.671074043425186]",NaN,NaN
4,4144117,1,4144117,31,Full,Good,22C65797-66EC-4C6B-9685-C3C0F9F64BF5,POINT(-74.01924788510804 40.62651478044688),E38293A1-2435-4748-886F-F2FAFF701EE4,Platanus x acerifolia - London planetree,...,2026-01-20 19:04:41.0000000,17216,10,2,44,41,Point,"[-74.01924788510804, 40.62651478044688]",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,4685394,1,4685394,12,Full,Good,06F2E856-DB9C-49FB-A11E-E151246FBF3C,POINT(-73.96456219869022 40.63726493229719),3F758A1E-51B2-4976-B7C6-3CC8226ED590,Acer platanoides 'Not Green Leaf' - 'Not Green...,...,NaN,13510,60,2,11,43,Point,"[-73.96456219869022, 40.63726493229719]",0,NaN
438,4685523,1,4685523,13,Full,Fair,2DCDD0CE-980E-4132-BDB4-5CACB41519C9,POINT(-73.97761991693181 40.61890378532121),28D15B4D-A82E-4664-9747-3289853BE896,Acer rubrum - red maple,...,2026-04-13 16:37:43.0000000,16867,2,2,18,39,Point,"[-73.97761991693181, 40.61890378532121]",NaN,NaN
439,4685834,1,4685834,NaN,Stump,Dead,09D32102-2ACA-4236-8196-D76CD1B03446,POINT(-73.98509884437783 40.63476553313637),32AE2E11-87C2-45CB-ABE2-C95184DDFD82,Fraxinus pennsylvanica - Green ash,...,2023-08-01 15:54:00.0000000,17621,2,2,18,39,Point,"[-73.98509884437783, 40.63476553313637]",18,NaN
440,4686014,1,4686014,5,Full,Good,D5D23A82-EC0B-4E32-B0AA-55C05FFE092F,POINT(-73.95823010107186 40.603148851495426),64735349-BBFA-4B72-9445-B24407677F90,Amelanchier - serviceberry,...,2022-01-14 18:17:27.0000000,13512,32,2,15,36,Point,"[-73.95823010107186, 40.603148851495426]",NaN,NaN
441,4686115,1,4686115,4,Retired,Dead,EA5B93FC-4996-4D87-98D3-6A45CF47B3D6,POINT(-73.93404211909912 40.67672164059946),22A1CC1F-A508-48AE-9B9C-1D0865953853,Zelkova serrata - Japanese zelkova,...,NaN,17615,16,2,49,49,Point,"[-73.93404211909912, 40.67672164059946]",0,NaN

#### get rows 700,000-799,999

In [21]:
# get next set of data
import requests
url = 'https://data.cityofnewyork.us/resource/hn5i-inap.json?$limit=99999&$offset=699999'
response = requests.get(url)

data = response.json()


# convert from json to pandas dataframe
df = pd.json_normalize(data)


# convert objectid field from string to integer to prepare for merging data
df['objectid'] = pd.to_numeric(df['objectid'])


# perform inner join using ID fields - treeID and objectID
df_7 = df_fav.merge(df, how='inner', left_on='treeId', right_on='objectid')
df_7

,treeId,numberOfTimesFavorited,objectid,dbh,tpstructure,tpcondition,stumpdiameter,plantingspaceglobalid,geometry,globalid,...,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,location.type,location.coordinates,riskrating,riskratingdate,planteddate
0,4686250,1,4686250,7,Full,Good,NaN,2BCD47E7-0555-4C8D-9B03-89E8CA354F4F,POINT(-73.95193949056852 40.69182931835801),8A6E00D0-82EB-420D-B154-6EBE291CBDB9,...,17212,69,2,38,51,Point,"[-73.95193949056852, 40.69182931835801]",5,2025-06-07 15:24:26.0000000,NaN
1,4686941,1,4686941,9,Full,Fair,NaN,7F0054EF-7D9A-412F-9AD6-309AF7F524F8,POINT(-73.9786132276175 40.61993207402463),DB3958F7-11CA-4B34-A6B8-CA79FFBBF3F4,...,16867,2,2,18,39,Point,"[-73.9786132276175, 40.61993207402463]",8,2026-04-09 17:56:03.0000000,NaN
2,4687273,1,4687273,3,Full,Good,NaN,321ABAE4-9C55-4787-A30B-1EB6537A8496,POINT(-73.75713676967342 40.74710773475168),BF89AA55-1E35-48AA-B590-C950744FE9D7,...,14506,26,3,16,69,Point,"[-73.75713676967342, 40.74710773475168]",5,2021-10-12 18:34:26.0000000,NaN
3,4687746,1,4687746,24,Full,Good,NaN,23977C6B-4E31-42B0-B318-B319C693E893,POINT(-73.77848248493987 40.76948368114901),5BB08CA8-B55E-4B67-8C72-65EBE745DB43,...,14196,26,3,20,69,Point,"[-73.77848248493987, 40.76948368114901]",7,2025-07-14 13:42:52.0000000,NaN
4,4687846,1,4687846,3,Full,Excellent,NaN,AB5AF431-02E4-4673-9D01-4621457B9016,POINT(-73.75817080077931 40.7471829479088),FA753B9B-476B-46B3-A274-F30BD6B6FABF,...,14506,26,3,16,69,Point,"[-73.75817080077931, 40.7471829479088]",5,2021-10-13 16:58:42.0000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,5115105,1,5115105,42,Full,Fair,NaN,A6B39770-9A53-4C25-8718-E1CDEC6388CA,POINT(-73.96263671430039 40.62727026130741),5B2849F5-D101-43B9-BB9A-F0579B2E93A7,...,13513,60,2,18,43,Point,"[-73.96263671430039, 40.62727026130741]",7,2022-01-06 14:40:38.0000000,NaN
161,5120735,1,5120735,42,Full,Good,NaN,DAAA6620-613F-4320-A76E-ED62120077AD,POINT(-73.82342308107606 40.796998937984675),F270B03E-2900-495F-B77A-28D6D87E73DF,...,14192,22,3,20,67,Point,"[-73.82342308107606, 40.796998937984675]",7,2022-01-18 12:47:41.0000000,NaN
162,5123131,1,5123131,3,Full,Good,NaN,39D6E95A-7242-4E00-BE0E-9EAB76C827E1,POINT(-73.90408243631697 40.69644967359128),CDE66054-F479-4FD7-98CC-CB8ED24F022A,...,15310,54,3,30,62,Point,"[-73.90408243631697, 40.69644967359128]",9,2017-11-27 11:40:00.0000000,NaN
163,5127759,1,5127759,3,Full,Good,NaN,D5F7333D-459F-4C65-91A7-346947F7A3D0,POINT(-73.90420015928551 40.69901516690843),09CA7BFC-0994-4156-AB58-CA139E3906C3,...,15310,54,3,30,62,Point,"[-73.90420015928551, 40.69901516690843]",NaN,NaN,2017-05-30 00:00:00.0000000
164,5127785,1,5127785,2,Full,Good,NaN,6FF8CB36-D7D6-40D4-BEB2-62D64BD6C956,POINT(-73.90417613920667 40.69635807063512),B92E61D2-08B2-4497-8CBF-F0A189E1CD26,...,15310,54,3,30,62,Point,"[-73.90417613920667, 40.69635807063512]",4,2018-04-23 12:46:10.0000000,2017-05-31 00:00:00.0000000

#### get rows 800,000-899,999

In [22]:
# get next set of data
import requests
url = 'https://data.cityofnewyork.us/resource/hn5i-inap.json?$limit=99999&$offset=799999'
response = requests.get(url)

data = response.json()


# convert from json to pandas dataframe
df = pd.json_normalize(data)


# convert objectid field from string toß
integer to prepare for merging data
df['objectid'] = pd.to_numeric(df['objectid'])


# perform inner join using ID fields - treeID and objectID
df_8 = df_fav.merge(df, how='inner', left_on='treeId', right_on='objectid')
df_8

SyntaxError: invalid syntax (4029415803.py, line 14)

#### get rows 900,000-999,999

In [ ]:
# get next set of data
import requests
url = 'https://data.cityofnewyork.us/resource/hn5i-inap.json?$limit=99999&$offset=899999'
response = requests.get(url)

data = response.json()


# convert from json to pandas dataframe
df = pd.json_normalize(data)


# convert objectid field from string to integer to prepare for merging data
df['objectid'] = pd.to_numeric(df['objectid'])


# perform inner join using ID fields - treeID and objectID
df_9 = df_fav.merge(df, how='inner', left_on='treeId', right_on='objectid')
df_9

#### get rows 1,000,000-1,100,000

In [ ]:
# get next set of data
import requests
url = 'https://data.cityofnewyork.us/resource/hn5i-inap.json?$limit=99999&$offset=999999'
response = requests.get(url)

data = response.json()


# convert from json to pandas dataframe
df = pd.json_normalize(data)
df

# convert objectid field from string to integer to prepare for merging data
df['objectid'] = pd.to_numeric(df['objectid'])


# perform inner join using ID fields - treeID and objectID4
df_10 = df_fav.merge(df, how='inner', left_on='treeId', right_on='objectid')
df_10

#### get rows 1,100,000-last row in dataset

In [ ]:
# get next set of data
import requests
url = 'https://data.cityofnewyork.us/resource/hn5i-inap.json?$limit=99999&$offset=1099999'
response = requests.get(url)

data = response.json()


# convert from json to pandas dataframe
df = pd.json_normalize(data)

# convert objectid field from string to integer to prepare for merging data
df['objectid'] = pd.to_numeric(df['objectid'])


# perform inner join using ID fields - treeID and objectID4
df_11 = df_fav.merge(df, how='inner', left_on='treeId', right_on='objectid')
df_11

In [ ]:
frames = [df_0, df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8, df_9, df_10, df_11]

df_merged = pd.concat(frames)
df_merged

In [ ]:
# save df to csv file
df_merged.to_csv('fav-trees.csv')